class Addcolumtoencuesta10modulo < ActiveRecord::Migration[5.2]
  def change


	add_column :encuesta, :p10_1, :string
  	add_column :encuesta, :p10_1_a, :string
  	add_column :encuesta, :p10_1_b, :string
  	add_column :encuesta, :p10_1_c, :string
  	add_column :encuesta, :p10_1_d, :string
  	add_column :encuesta, :p10_1_e, :string
  	add_column :encuesta, :p10_1_f, :string
  	add_column :encuesta, :p10_2, :string
	add_column :encuesta, :p10_t1_a, :string
  	add_column :encuesta, :p10_t1_a_1, :string
  	add_column :encuesta, :p10_t1_a_2, :string
  	add_column :encuesta, :p10_t1_a_3, :string
  	add_column :encuesta, :p10_t1_a_4, :string
  	add_column :encuesta, :p10_t1_b, :string
  	add_column :encuesta, :p10_t1_b_1, :string
  	add_column :encuesta, :p10_t1_b_2, :string
  	add_column :encuesta, :p10_t1_b_3, :string
  	add_column :encuesta, :p10_t1_b_4, :string
  	add_column :encuesta, :p10_t1_c, :string
  	add_column :encuesta, :p10_t1_c_1, :string
  	add_column :encuesta, :p10_t1_c_2, :string
  	add_column :encuesta, :p10_t1_c_3, :string
  	add_column :encuesta, :p10_t1_c_4, :string
  	add_column :encuesta, :p10_3, :string
  	add_column :encuesta, :p10_t1a_a, :string
  	add_column :encuesta, :p10_t1a_a_1, :string
  	add_column :encuesta, :p10_t1a_a_2, :string
  	add_column :encuesta, :p10_t1a_a_3, :string
  	add_column :encuesta, :p10_t1a_a_4, :string
  	add_column :encuesta, :p10_t1a_a_5, :string
  	add_column :encuesta, :p10_t1a_b, :string
  	add_column :encuesta, :p10_t1a_b_1, :string
  	add_column :encuesta, :p10_t1a_b_2, :string
  	add_column :encuesta, :p10_t1a_b_3, :string
  	add_column :encuesta, :p10_t1a_b_4, :string
  	add_column :encuesta, :p10_t1a_b_5, :string
  	add_column :encuesta, :p10_t1a_c, :string
  	add_column :encuesta, :p10_t1a_c_1, :string
  	add_column :encuesta, :p10_t1a_c_2, :string
  	add_column :encuesta, :p10_t1a_c_3, :string
  	add_column :encuesta, :p10_t1a_c_4, :string
  	add_column :encuesta, :p10_t1a_c_5, :string
  	add_column :encuesta, :p10_4, :string
  	add_column :encuesta, :p10_4_a, :string
  	add_column :encuesta, :p10_4_b, :string
  	add_column :encuesta, :p10_4_c, :string
  	add_column :encuesta, :p10_4_d, :string
  	add_column :encuesta, :p10_4_e, :string
  	add_column :encuesta, :p10_4_f, :string
	add_column :encuesta, :p10_4_g, :string
  	add_column :encuesta, :p10_4_h, :string
  	add_column :encuesta, :p10_4_i, :string
	add_column :encuesta, :p10_t2_a1_1, :string
	add_column :encuesta, :p10_t2_a1_2, :string
	add_column :encuesta, :p10_t2_a1_3, :string
	add_column :encuesta, :p10_t2_a1_4, :string
	add_column :encuesta, :p10_t2_a1_5, :string
	add_column :encuesta, :p10_t2_a2_1, :string
	add_column :encuesta, :p10_t2_a2_2, :string
	add_column :encuesta, :p10_t2_a2_3, :string
	add_column :encuesta, :p10_t2_a2_4, :string
	add_column :encuesta, :p10_t2_a2_5, :string
	add_column :encuesta, :p10_t2_a3_1, :string
	add_column :encuesta, :p10_t2_a3_2, :string
	add_column :encuesta, :p10_t2_a3_3, :string
	add_column :encuesta, :p10_t2_a3_4, :string
	add_column :encuesta, :p10_t2_a3_5, :string
	add_column :encuesta, :p10_t2_b1_1, :string
	add_column :encuesta, :p10_t2_b1_2, :string
	add_column :encuesta, :p10_t2_b1_3, :string
	add_column :encuesta, :p10_t2_b1_4, :string
	add_column :encuesta, :p10_t2_b1_5, :string
	add_column :encuesta, :p10_t2_b2_1, :string
	add_column :encuesta, :p10_t2_b2_2, :string
	add_column :encuesta, :p10_t2_b2_3, :string
	add_column :encuesta, :p10_t2_b2_4, :string
	add_column :encuesta, :p10_t2_b2_5, :string
	add_column :encuesta, :p10_t2_c1_1, :string
	add_column :encuesta, :p10_t2_c1_2, :string
	add_column :encuesta, :p10_t2_c1_3, :string
	add_column :encuesta, :p10_t2_c1_4, :string
	add_column :encuesta, :p10_t2_c1_5, :string
	add_column :encuesta, :p10_t2_c2_1, :string
	add_column :encuesta, :p10_t2_c2_2, :string
	add_column :encuesta, :p10_t2_c2_3, :string
	add_column :encuesta, :p10_t2_c2_4, :string
	add_column :encuesta, :p10_t2_c2_5, :string
	add_column :encuesta, :p10_t2_d1_1, :string
	add_column :encuesta, :p10_t2_d1_2, :string
	add_column :encuesta, :p10_t2_d1_3, :string
	add_column :encuesta, :p10_t2_d1_4, :string
	add_column :encuesta, :p10_t2_d1_5, :string
	add_column :encuesta, :p10_t2_d2_1, :string
	add_column :encuesta, :p10_t2_d2_2, :string
	add_column :encuesta, :p10_t2_d2_3, :string
	add_column :encuesta, :p10_t2_d2_4, :string
	add_column :encuesta, :p10_t2_d2_5, :string
	add_column :encuesta, :p10_t2_d3, :string
	add_column :encuesta, :p10_t2_d3_1, :string
	add_column :encuesta, :p10_t2_d3_2, :string
	add_column :encuesta, :p10_t2_d3_3, :string
	add_column :encuesta, :p10_t2_d3_4, :string
	add_column :encuesta, :p10_t2_d3_5, :string
	add_column :encuesta, :p10_t2_d4_1, :string
	add_column :encuesta, :p10_t2_d4_2, :string
	add_column :encuesta, :p10_t2_d4_3, :string
	add_column :encuesta, :p10_t2_d4_4, :string
	add_column :encuesta, :p10_t2_d4_5, :string
	add_column :encuesta, :p10_t2_d5_1, :string
	add_column :encuesta, :p10_t2_d5_2, :string
	add_column :encuesta, :p10_t2_d5_3, :string
	add_column :encuesta, :p10_t2_d5_4, :string
	add_column :encuesta, :p10_t2_d5_5, :string
	add_column :encuesta, :p10_t2_d6_1, :string
	add_column :encuesta, :p10_t2_d6_2, :string
	add_column :encuesta, :p10_t2_d6_3, :string
	add_column :encuesta, :p10_t2_d6_4, :string
	add_column :encuesta, :p10_t2_d6_5, :string
	add_column :encuesta, :p10_t2_e1_1, :string
	add_column :encuesta, :p10_t2_e1_2, :string
	add_column :encuesta, :p10_t2_e1_3, :string
	add_column :encuesta, :p10_t2_e1_4, :string
	add_column :encuesta, :p10_t2_e1_5, :string
	add_column :encuesta, :p10_t2_e2_ck, :string
	add_column :encuesta, :p10_t2_e2_kc, :string
	add_column :encuesta, :p10_t2_e2_4, :string
	add_column :encuesta, :p10_t2_e2_5, :string
	add_column :encuesta, :p10_t2_e3_1, :string
	add_column :encuesta, :p10_t2_e3_2, :string
	add_column :encuesta, :p10_t2_e3_3, :string
	add_column :encuesta, :p10_t2_e3_4, :string
	add_column :encuesta, :p10_t2_e3_5, :string
	add_column :encuesta, :p10_t2_f, :string
	add_column :encuesta, :p10_t2_f1_1, :string
	add_column :encuesta, :p10_t2_f1_2, :string
	add_column :encuesta, :p10_t2_f1_3, :string
	add_column :encuesta, :p10_t2_f1_4, :string
	add_column :encuesta, :p10_t2_f1_5, :string
	add_column :encuesta, :p10_t2_f2_cb, :string
	add_column :encuesta, :p10_t2_f2_db, :string
	add_column :encuesta, :p10_t2_f2_kb, :string
	add_column :encuesta, :p10_t2_f2_5, :string
	add_column :encuesta, :p10_t2_g, :string
	add_column :encuesta, :p10_t2_g_5, :string
	add_column :encuesta, :p10_t2_h, :string
	add_column :encuesta, :p10_t2_h_1, :string
	add_column :encuesta, :p10_t2_h_2, :string
	add_column :encuesta, :p10_t2_h_3, :string
	add_column :encuesta, :p10_t2_h_4, :string
	add_column :encuesta, :p10_t2_h_5, :string
	add_column :encuesta, :p10_6, :string
	add_column :encuesta, :p10_t3_a1_a, :string
	add_column :encuesta, :p10_t3_a1_b, :string
	add_column :encuesta, :p10_t3_a_1_a, :string
	add_column :encuesta, :p10_t3_a_1_b, :string
	add_column :encuesta, :p10_t3_a_1_c, :string
	add_column :encuesta, :p10_t3_a_1_d, :string
	add_column :encuesta, :p10_t3_a_2_a, :string
	add_column :encuesta, :p10_t3_a_2_b, :string
	add_column :encuesta, :p10_t3_a_2_c, :string
	add_column :encuesta, :p10_t3_a_2_d, :string
	add_column :encuesta, :p10_t3_b_a, :string
	add_column :encuesta, :p10_t3_b_b, :string
	add_column :encuesta, :p10_t3_b_c, :string
	add_column :encuesta, :p10_t3_b_d, :string
	add_column :encuesta, :p10_t3_c_a, :string
	add_column :encuesta, :p10_t3_c_b, :string
	add_column :encuesta, :p10_t3_c_c, :string
	add_column :encuesta, :p10_t3_c_d, :string
	add_column :encuesta, :p10_t3_d_a, :string
	add_column :encuesta, :p10_t3_d_b, :string
	add_column :encuesta, :p10_t3_d_c, :string
	add_column :encuesta, :p10_t3_d_d, :string
	add_column :encuesta, :p10_t3_e_a, :string
	add_column :encuesta, :p10_t3_e_b, :string
	add_column :encuesta, :p10_t3_e_c, :string
	add_column :encuesta, :p10_t3_e_d, :string
	add_column :encuesta, :p10_t3_f_a, :string
	add_column :encuesta, :p10_t3_f_b, :string
	add_column :encuesta, :p10_t3_f_c, :string
	add_column :encuesta, :p10_t3_f_d, :string
	add_column :encuesta, :p10_t3_g_a, :string
	add_column :encuesta, :p10_t3_g_b, :string
	add_column :encuesta, :p10_t3_g_c, :string
	add_column :encuesta, :p10_t3_g_d, :string
	add_column :encuesta, :p10_7a, :string
	add_column :encuesta, :p10_7b, :string

  end
end
