class Addcolumtoencuesta7modulo < ActiveRecord::Migration[5.2]
  def change

	add_column :encuesta, :p7_59_1, :string
  	add_column :encuesta, :p7_59_2, :string
  	add_column :encuesta, :p7_59_3, :string
  	add_column :encuesta, :p7_59_4, :string
  	add_column :encuesta, :p7_59_5, :string
  	add_column :encuesta, :p7_59_6, :string
  	add_column :encuesta, :p7_59_7, :string
  	add_column :encuesta, :p7_59_8, :string

  	add_column :encuesta, :p7_60_1, :string
  	add_column :encuesta, :p7_60_2, :string
  	add_column :encuesta, :p7_60_3, :string
  	add_column :encuesta, :p7_60_4, :string
  	add_column :encuesta, :p7_60_5, :string
  	add_column :encuesta, :p7_60_6, :string
  	add_column :encuesta, :p7_60_7, :string
  	add_column :encuesta, :p7_60_8, :string

  	add_column :encuesta, :p7_61_1, :string
  	add_column :encuesta, :p7_61_2, :string
  	add_column :encuesta, :p7_61_3, :string
  	add_column :encuesta, :p7_61_4, :string
  	add_column :encuesta, :p7_61_5, :string
  	add_column :encuesta, :p7_61_6, :string
  	add_column :encuesta, :p7_61_7, :string
  	add_column :encuesta, :p7_61_8, :string

  	add_column :encuesta, :p7_62_1, :string
  	add_column :encuesta, :p7_62_2, :string
  	add_column :encuesta, :p7_62_3, :string
  	add_column :encuesta, :p7_62_4, :string
  	add_column :encuesta, :p7_62_5, :string
  	add_column :encuesta, :p7_62_6, :string
  	add_column :encuesta, :p7_62_7, :string
  	add_column :encuesta, :p7_62_8, :string

  	add_column :encuesta, :p7_63_1, :string
  	add_column :encuesta, :p7_63_2, :string
  	add_column :encuesta, :p7_63_3, :string
  	add_column :encuesta, :p7_63_4, :string
  	add_column :encuesta, :p7_63_5, :string
  	add_column :encuesta, :p7_63_6, :string
  	add_column :encuesta, :p7_63_7, :string
  	add_column :encuesta, :p7_63_8, :string

  	add_column :encuesta, :p7_64_1, :string
  	add_column :encuesta, :p7_64_2, :string
  	add_column :encuesta, :p7_64_3, :string
  	add_column :encuesta, :p7_64_4, :string
  	add_column :encuesta, :p7_64_5, :string
  	add_column :encuesta, :p7_64_6, :string
  	add_column :encuesta, :p7_64_7, :string
  	add_column :encuesta, :p7_64_8, :string

  	add_column :encuesta, :p7_65_1, :string
  	add_column :encuesta, :p7_65_2, :string
  	add_column :encuesta, :p7_65_3, :string
  	add_column :encuesta, :p7_65_4, :string
  	add_column :encuesta, :p7_65_5, :string
  	add_column :encuesta, :p7_65_6, :string
  	add_column :encuesta, :p7_65_7, :string
  	add_column :encuesta, :p7_65_8, :string

  	add_column :encuesta, :p7_66_1, :string
  	add_column :encuesta, :p7_66_2, :string
  	add_column :encuesta, :p7_66_3, :string
  	add_column :encuesta, :p7_66_4, :string
  	add_column :encuesta, :p7_66_5, :string
  	add_column :encuesta, :p7_66_6, :string
  	add_column :encuesta, :p7_66_7, :string
  	add_column :encuesta, :p7_66_8, :string

  	add_column :encuesta, :p7_67_1_a, :string
  	add_column :encuesta, :p7_67_1_b, :string
  	add_column :encuesta, :p7_67_2_a, :string
  	add_column :encuesta, :p7_67_2_b, :string
  	add_column :encuesta, :p7_67_3_a, :string
  	add_column :encuesta, :p7_67_3_b, :string
  	add_column :encuesta, :p7_67_4_a, :string
  	add_column :encuesta, :p7_67_4_b, :string
  	add_column :encuesta, :p7_67_5_a, :string
  	add_column :encuesta, :p7_67_5_b, :string
  	add_column :encuesta, :p7_67_6_a, :string
  	add_column :encuesta, :p7_67_6_b, :string
  	add_column :encuesta, :p7_67_7_a, :string
  	add_column :encuesta, :p7_67_7_b, :string
  	add_column :encuesta, :p7_67_8_a, :string
  	add_column :encuesta, :p7_67_8_b, :string

  	add_column :encuesta, :p7_68_1, :string
  	add_column :encuesta, :p7_68_2, :string
  	add_column :encuesta, :p7_68_3, :string
  	add_column :encuesta, :p7_68_4, :string
  	add_column :encuesta, :p7_68_5, :string
  	add_column :encuesta, :p7_68_6, :string
  	add_column :encuesta, :p7_68_7, :string
  	add_column :encuesta, :p7_68_8, :string
	add_column :encuesta, :p7_68o_1, :string
  	add_column :encuesta, :p7_68o_2, :string
  	add_column :encuesta, :p7_68o_3, :string
  	add_column :encuesta, :p7_68o_4, :string
  	add_column :encuesta, :p7_68o_5, :string
  	add_column :encuesta, :p7_68o_6, :string
  	add_column :encuesta, :p7_68o_7, :string
  	add_column :encuesta, :p7_68o_8, :string

  	add_column :encuesta, :p7_69_1, :string
  	add_column :encuesta, :p7_69_2, :string
  	add_column :encuesta, :p7_69_3, :string
  	add_column :encuesta, :p7_69_4, :string
  	add_column :encuesta, :p7_69_5, :string
  	add_column :encuesta, :p7_69_6, :string
  	add_column :encuesta, :p7_69_7, :string
  	add_column :encuesta, :p7_69_8, :string

  	add_column :encuesta, :p7_70_1, :string
  	add_column :encuesta, :p7_70_2, :string
  	add_column :encuesta, :p7_70_3, :string
  	add_column :encuesta, :p7_70_4, :string
  	add_column :encuesta, :p7_70_5, :string
  	add_column :encuesta, :p7_70_6, :string
  	add_column :encuesta, :p7_70_7, :string
  	add_column :encuesta, :p7_70_8, :string

  	add_column :encuesta, :p7_71a_1, :string
  	add_column :encuesta, :p7_71a_2, :string
  	add_column :encuesta, :p7_71a_3, :string
  	add_column :encuesta, :p7_71a_4, :string
  	add_column :encuesta, :p7_71a_5, :string
  	add_column :encuesta, :p7_71a_6, :string
  	add_column :encuesta, :p7_71a_7, :string
  	add_column :encuesta, :p7_71a_8, :string
	add_column :encuesta, :p7_71b_1, :string
  	add_column :encuesta, :p7_71b_2, :string
  	add_column :encuesta, :p7_71b_3, :string
  	add_column :encuesta, :p7_71b_4, :string
  	add_column :encuesta, :p7_71b_5, :string
  	add_column :encuesta, :p7_71b_6, :string
  	add_column :encuesta, :p7_71b_7, :string
  	add_column :encuesta, :p7_71b_8, :string

  	add_column :encuesta, :p7_72_1, :string
  	add_column :encuesta, :p7_72_2, :string
  	add_column :encuesta, :p7_72_3, :string
  	add_column :encuesta, :p7_72_4, :string
  	add_column :encuesta, :p7_72_5, :string
  	add_column :encuesta, :p7_72_6, :string
  	add_column :encuesta, :p7_72_7, :string
  	add_column :encuesta, :p7_72_8, :string

  	add_column :encuesta, :p7_73a_1, :string
  	add_column :encuesta, :p7_73a_2, :string
  	add_column :encuesta, :p7_73a_3, :string
  	add_column :encuesta, :p7_73a_4, :string
  	add_column :encuesta, :p7_73a_5, :string
  	add_column :encuesta, :p7_73a_6, :string
  	add_column :encuesta, :p7_73a_7, :string
  	add_column :encuesta, :p7_73a_8, :string
	add_column :encuesta, :p7_73b_1, :string
  	add_column :encuesta, :p7_73b_2, :string
  	add_column :encuesta, :p7_73b_3, :string
  	add_column :encuesta, :p7_73b_4, :string
  	add_column :encuesta, :p7_73b_5, :string
  	add_column :encuesta, :p7_73b_6, :string
  	add_column :encuesta, :p7_73b_7, :string
  	add_column :encuesta, :p7_73b_8, :string

  	add_column :encuesta, :p7_74a_1, :string
  	add_column :encuesta, :p7_74a_2, :string
  	add_column :encuesta, :p7_74a_3, :string
  	add_column :encuesta, :p7_74a_4, :string
  	add_column :encuesta, :p7_74a_5, :string
  	add_column :encuesta, :p7_74a_6, :string
  	add_column :encuesta, :p7_74a_7, :string
  	add_column :encuesta, :p7_74a_8, :string
	add_column :encuesta, :p7_74b_1, :string
  	add_column :encuesta, :p7_74b_2, :string
  	add_column :encuesta, :p7_74b_3, :string
  	add_column :encuesta, :p7_74b_4, :string
  	add_column :encuesta, :p7_74b_5, :string
  	add_column :encuesta, :p7_74b_6, :string
  	add_column :encuesta, :p7_74b_7, :string
  	add_column :encuesta, :p7_74b_8, :string

  	add_column :encuesta, :p7_75a_1, :string
  	add_column :encuesta, :p7_75a_2, :string
  	add_column :encuesta, :p7_75a_3, :string
  	add_column :encuesta, :p7_75a_4, :string
  	add_column :encuesta, :p7_75a_5, :string
  	add_column :encuesta, :p7_75a_6, :string
  	add_column :encuesta, :p7_75a_7, :string
  	add_column :encuesta, :p7_75a_8, :string
	add_column :encuesta, :p7_75b_1, :string
  	add_column :encuesta, :p7_75b_2, :string
  	add_column :encuesta, :p7_75b_3, :string
  	add_column :encuesta, :p7_75b_4, :string
  	add_column :encuesta, :p7_75b_5, :string
  	add_column :encuesta, :p7_75b_6, :string
  	add_column :encuesta, :p7_75b_7, :string
  	add_column :encuesta, :p7_75b_8, :string

  	add_column :encuesta, :p7_76a_1, :string
  	add_column :encuesta, :p7_76a_2, :string
  	add_column :encuesta, :p7_76a_3, :string
  	add_column :encuesta, :p7_76a_4, :string
  	add_column :encuesta, :p7_76a_5, :string
  	add_column :encuesta, :p7_76a_6, :string
  	add_column :encuesta, :p7_76a_7, :string
  	add_column :encuesta, :p7_76a_8, :string
	add_column :encuesta, :p7_76b_1, :string
  	add_column :encuesta, :p7_76b_2, :string
  	add_column :encuesta, :p7_76b_3, :string
  	add_column :encuesta, :p7_76b_4, :string
  	add_column :encuesta, :p7_76b_5, :string
  	add_column :encuesta, :p7_76b_6, :string
  	add_column :encuesta, :p7_76b_7, :string
  	add_column :encuesta, :p7_76b_8, :string

  	add_column :encuesta, :p7_77a_1, :string
  	add_column :encuesta, :p7_77a_2, :string
  	add_column :encuesta, :p7_77a_3, :string
  	add_column :encuesta, :p7_77a_4, :string
  	add_column :encuesta, :p7_77a_5, :string
  	add_column :encuesta, :p7_77a_6, :string
  	add_column :encuesta, :p7_77a_7, :string
  	add_column :encuesta, :p7_77a_8, :string
	add_column :encuesta, :p7_77b_1, :string
  	add_column :encuesta, :p7_77b_2, :string
  	add_column :encuesta, :p7_77b_3, :string
  	add_column :encuesta, :p7_77b_4, :string
  	add_column :encuesta, :p7_77b_5, :string
  	add_column :encuesta, :p7_77b_6, :string
  	add_column :encuesta, :p7_77b_7, :string
  	add_column :encuesta, :p7_77b_8, :string

  	add_column :encuesta, :p7_78a_1, :string
  	add_column :encuesta, :p7_78a_2, :string
  	add_column :encuesta, :p7_78a_3, :string
  	add_column :encuesta, :p7_78a_4, :string
  	add_column :encuesta, :p7_78a_5, :string
  	add_column :encuesta, :p7_78a_6, :string
  	add_column :encuesta, :p7_78a_7, :string
  	add_column :encuesta, :p7_78a_8, :string
	add_column :encuesta, :p7_78b_1, :string
  	add_column :encuesta, :p7_78b_2, :string
  	add_column :encuesta, :p7_78b_3, :string
  	add_column :encuesta, :p7_78b_4, :string
  	add_column :encuesta, :p7_78b_5, :string
  	add_column :encuesta, :p7_78b_6, :string
  	add_column :encuesta, :p7_78b_7, :string
  	add_column :encuesta, :p7_78b_8, :string

  	add_column :encuesta, :p7_79a_1, :string
  	add_column :encuesta, :p7_79a_2, :string
  	add_column :encuesta, :p7_79a_3, :string
  	add_column :encuesta, :p7_79a_4, :string
  	add_column :encuesta, :p7_79a_5, :string
  	add_column :encuesta, :p7_79a_6, :string
  	add_column :encuesta, :p7_79a_7, :string
  	add_column :encuesta, :p7_79a_8, :string
	add_column :encuesta, :p7_79b_1, :string
  	add_column :encuesta, :p7_79b_2, :string
  	add_column :encuesta, :p7_79b_3, :string
  	add_column :encuesta, :p7_79b_4, :string
  	add_column :encuesta, :p7_79b_5, :string
  	add_column :encuesta, :p7_79b_6, :string
  	add_column :encuesta, :p7_79b_7, :string
  	add_column :encuesta, :p7_79b_8, :string

  	add_column :encuesta, :p7_80a_1, :string
  	add_column :encuesta, :p7_80a_2, :string
  	add_column :encuesta, :p7_80a_3, :string
  	add_column :encuesta, :p7_80a_4, :string
  	add_column :encuesta, :p7_80a_5, :string
  	add_column :encuesta, :p7_80a_6, :string
  	add_column :encuesta, :p7_80a_7, :string
  	add_column :encuesta, :p7_80a_8, :string
	add_column :encuesta, :p7_80b_1, :string
  	add_column :encuesta, :p7_80b_2, :string
  	add_column :encuesta, :p7_80b_3, :string
  	add_column :encuesta, :p7_80b_4, :string
  	add_column :encuesta, :p7_80b_5, :string
  	add_column :encuesta, :p7_80b_6, :string
  	add_column :encuesta, :p7_80b_7, :string
  	add_column :encuesta, :p7_80b_8, :string

  	add_column :encuesta, :p7_81a_1, :string
  	add_column :encuesta, :p7_81a_2, :string
  	add_column :encuesta, :p7_81a_3, :string
  	add_column :encuesta, :p7_81a_4, :string
  	add_column :encuesta, :p7_81a_5, :string
  	add_column :encuesta, :p7_81a_6, :string
  	add_column :encuesta, :p7_81a_7, :string
  	add_column :encuesta, :p7_81a_8, :string
	add_column :encuesta, :p7_81b_1, :string
  	add_column :encuesta, :p7_81b_2, :string
  	add_column :encuesta, :p7_81b_3, :string
  	add_column :encuesta, :p7_81b_4, :string
  	add_column :encuesta, :p7_81b_5, :string
  	add_column :encuesta, :p7_81b_6, :string
  	add_column :encuesta, :p7_81b_7, :string
  	add_column :encuesta, :p7_81b_8, :string
	add_column :encuesta, :p7_81c_1, :string
  	add_column :encuesta, :p7_81c_2, :string
  	add_column :encuesta, :p7_81c_3, :string
  	add_column :encuesta, :p7_81c_4, :string
  	add_column :encuesta, :p7_81c_5, :string
  	add_column :encuesta, :p7_81c_6, :string
  	add_column :encuesta, :p7_81c_7, :string
  	add_column :encuesta, :p7_81c_8, :string

  	add_column :encuesta, :p7_82_1, :string
  	add_column :encuesta, :p7_82_2, :string
  	add_column :encuesta, :p7_82_3, :string
  	add_column :encuesta, :p7_82_4, :string
  	add_column :encuesta, :p7_82_5, :string
  	add_column :encuesta, :p7_82_6, :string
  	add_column :encuesta, :p7_82_7, :string
  	add_column :encuesta, :p7_82_8, :string

  	add_column :encuesta, :p7_83a_1, :string
  	add_column :encuesta, :p7_83a_2, :string
  	add_column :encuesta, :p7_83a_3, :string
  	add_column :encuesta, :p7_83a_4, :string
  	add_column :encuesta, :p7_83a_5, :string
  	add_column :encuesta, :p7_83a_6, :string
  	add_column :encuesta, :p7_83a_7, :string
  	add_column :encuesta, :p7_83a_8, :string
	add_column :encuesta, :p7_83b_1, :string
  	add_column :encuesta, :p7_83b_2, :string
  	add_column :encuesta, :p7_83b_3, :string
  	add_column :encuesta, :p7_83b_4, :string
  	add_column :encuesta, :p7_83b_5, :string
  	add_column :encuesta, :p7_83b_6, :string
  	add_column :encuesta, :p7_83b_7, :string
  	add_column :encuesta, :p7_83b_8, :string

  	add_column :encuesta, :p7_84_1, :string
  	add_column :encuesta, :p7_84_2, :string
  	add_column :encuesta, :p7_84_3, :string
  	add_column :encuesta, :p7_84_4, :string
  	add_column :encuesta, :p7_84_5, :string
  	add_column :encuesta, :p7_84_6, :string
  	add_column :encuesta, :p7_84_7, :string
  	add_column :encuesta, :p7_84_8, :string
	
  	add_column :encuesta, :p7_85_1, :string
  	add_column :encuesta, :p7_85_2, :string
  	add_column :encuesta, :p7_85_3, :string
  	add_column :encuesta, :p7_85_4, :string
  	add_column :encuesta, :p7_85_5, :string
  	add_column :encuesta, :p7_85_6, :string
  	add_column :encuesta, :p7_85_7, :string
  	add_column :encuesta, :p7_85_8, :string

  	add_column :encuesta, :p7_86_1, :string
  	add_column :encuesta, :p7_86_2, :string
  	add_column :encuesta, :p7_86_3, :string
  	add_column :encuesta, :p7_86_4, :string
  	add_column :encuesta, :p7_86_5, :string
  	add_column :encuesta, :p7_86_6, :string
  	add_column :encuesta, :p7_86_7, :string
  	add_column :encuesta, :p7_86_8, :string

  	add_column :encuesta, :p7_87a_1, :string
  	add_column :encuesta, :p7_87a_2, :string
  	add_column :encuesta, :p7_87a_3, :string
  	add_column :encuesta, :p7_87a_4, :string
  	add_column :encuesta, :p7_87a_5, :string
  	add_column :encuesta, :p7_87a_6, :string
  	add_column :encuesta, :p7_87a_7, :string
  	add_column :encuesta, :p7_87a_8, :string
	add_column :encuesta, :p7_87b_1, :string
  	add_column :encuesta, :p7_87b_2, :string
  	add_column :encuesta, :p7_87b_3, :string
  	add_column :encuesta, :p7_87b_4, :string
  	add_column :encuesta, :p7_87b_5, :string
  	add_column :encuesta, :p7_87b_6, :string
  	add_column :encuesta, :p7_87b_7, :string
  	add_column :encuesta, :p7_87b_8, :string


  	add_column :encuesta, :p7_88_1, :string
  	add_column :encuesta, :p7_88_2, :string
  	add_column :encuesta, :p7_88_3, :string
  	add_column :encuesta, :p7_88_4, :string
  	add_column :encuesta, :p7_88_5, :string
  	add_column :encuesta, :p7_88_6, :string
  	add_column :encuesta, :p7_88_7, :string
  	add_column :encuesta, :p7_88_8, :string

  	add_column :encuesta, :p7_89_1, :string
  	add_column :encuesta, :p7_89_2, :string
  	add_column :encuesta, :p7_89_3, :string
  	add_column :encuesta, :p7_89_4, :string
  	add_column :encuesta, :p7_89_5, :string
  	add_column :encuesta, :p7_89_6, :string
  	add_column :encuesta, :p7_89_7, :string
  	add_column :encuesta, :p7_89_8, :string

  	add_column :encuesta, :p7_90_1, :string
  	add_column :encuesta, :p7_90_2, :string
  	add_column :encuesta, :p7_90_3, :string
  	add_column :encuesta, :p7_90_4, :string
  	add_column :encuesta, :p7_90_5, :string
  	add_column :encuesta, :p7_90_6, :string
  	add_column :encuesta, :p7_90_7, :string
  	add_column :encuesta, :p7_90_8, :string

  	add_column :encuesta, :p7_91a_1, :string
  	add_column :encuesta, :p7_91a_2, :string
  	add_column :encuesta, :p7_91a_3, :string
  	add_column :encuesta, :p7_91a_4, :string
  	add_column :encuesta, :p7_91a_5, :string
  	add_column :encuesta, :p7_91a_6, :string
  	add_column :encuesta, :p7_91a_7, :string
  	add_column :encuesta, :p7_91a_8, :string
	add_column :encuesta, :p7_91b_1, :string
  	add_column :encuesta, :p7_91b_2, :string
  	add_column :encuesta, :p7_91b_3, :string
  	add_column :encuesta, :p7_91b_4, :string
  	add_column :encuesta, :p7_91b_5, :string
  	add_column :encuesta, :p7_91b_6, :string
  	add_column :encuesta, :p7_91b_7, :string
  	add_column :encuesta, :p7_91b_8, :string

  	add_column :encuesta, :p7_92_1, :string
  	add_column :encuesta, :p7_92_2, :string
  	add_column :encuesta, :p7_92_3, :string
  	add_column :encuesta, :p7_92_4, :string
  	add_column :encuesta, :p7_92_5, :string
  	add_column :encuesta, :p7_92_6, :string
  	add_column :encuesta, :p7_92_7, :string
  	add_column :encuesta, :p7_92_8, :string

  	add_column :encuesta, :p7_93a_1, :string
  	add_column :encuesta, :p7_93a_2, :string
  	add_column :encuesta, :p7_93a_3, :string
  	add_column :encuesta, :p7_93a_4, :string
  	add_column :encuesta, :p7_93a_5, :string
  	add_column :encuesta, :p7_93a_6, :string
  	add_column :encuesta, :p7_93a_7, :string
  	add_column :encuesta, :p7_93a_8, :string
	add_column :encuesta, :p7_93b_1, :string
  	add_column :encuesta, :p7_93b_2, :string
  	add_column :encuesta, :p7_93b_3, :string
  	add_column :encuesta, :p7_93b_4, :string
  	add_column :encuesta, :p7_93b_5, :string
  	add_column :encuesta, :p7_93b_6, :string
  	add_column :encuesta, :p7_93b_7, :string
  	add_column :encuesta, :p7_93b_8, :string
	add_column :encuesta, :p7_93c_1, :string
  	add_column :encuesta, :p7_93c_2, :string
  	add_column :encuesta, :p7_93c_3, :string
  	add_column :encuesta, :p7_93c_4, :string
  	add_column :encuesta, :p7_93c_5, :string
  	add_column :encuesta, :p7_93c_6, :string
  	add_column :encuesta, :p7_93c_7, :string
  	add_column :encuesta, :p7_93c_8, :string
  	
  end
end
