class Addcolumtoencuesta4modulo < ActiveRecord::Migration[5.2]
  def change

	add_column :encuesta, :p4_33_1, :string
  	add_column :encuesta, :p4_33_2, :string
  	add_column :encuesta, :p4_33_3, :string
  	add_column :encuesta, :p4_33_4, :string
  	add_column :encuesta, :p4_33_5, :string
  	add_column :encuesta, :p4_33_6, :string
  	add_column :encuesta, :p4_33_7, :string
  	add_column :encuesta, :p4_33_8, :string
  	add_column :encuesta, :p4_34_1, :string
  	add_column :encuesta, :p4_34_2, :string
  	add_column :encuesta, :p4_34_3, :string
  	add_column :encuesta, :p4_34_4, :string
  	add_column :encuesta, :p4_34_5, :string
  	add_column :encuesta, :p4_34_6, :string
  	add_column :encuesta, :p4_34_7, :string
  	add_column :encuesta, :p4_34_8, :string
  	add_column :encuesta, :p4_35_1, :string
  	add_column :encuesta, :p4_35_2, :string
  	add_column :encuesta, :p4_35_3, :string
  	add_column :encuesta, :p4_35_4, :string
  	add_column :encuesta, :p4_35_5, :string
  	add_column :encuesta, :p4_35_6, :string
  	add_column :encuesta, :p4_35_7, :string
  	add_column :encuesta, :p4_35_8, :string
  	add_column :encuesta, :p4_36_1, :string
  	add_column :encuesta, :p4_36_2, :string
  	add_column :encuesta, :p4_36_3, :string
  	add_column :encuesta, :p4_36_4, :string
  	add_column :encuesta, :p4_36_5, :string
  	add_column :encuesta, :p4_36_6, :string
  	add_column :encuesta, :p4_36_7, :string
  	add_column :encuesta, :p4_36_8, :string
  	add_column :encuesta, :p4_37_1, :string
  	add_column :encuesta, :p4_37_2, :string
  	add_column :encuesta, :p4_37_3, :string
  	add_column :encuesta, :p4_37_4, :string
  	add_column :encuesta, :p4_37_5, :string
  	add_column :encuesta, :p4_37_6, :string
  	add_column :encuesta, :p4_37_7, :string
  	add_column :encuesta, :p4_37_8, :string
  	add_column :encuesta, :p4_38_1, :string
  	add_column :encuesta, :p4_38_2, :string
  	add_column :encuesta, :p4_38_3, :string
  	add_column :encuesta, :p4_38_4, :string
  	add_column :encuesta, :p4_38_5, :string
  	add_column :encuesta, :p4_38_6, :string
  	add_column :encuesta, :p4_38_7, :string
  	add_column :encuesta, :p4_38_8, :string
  	add_column :encuesta, :p4_39_1, :string
  	add_column :encuesta, :p4_39_2, :string
  	add_column :encuesta, :p4_39_3, :string
  	add_column :encuesta, :p4_39_4, :string
  	add_column :encuesta, :p4_39_5, :string
  	add_column :encuesta, :p4_39_6, :string
  	add_column :encuesta, :p4_39_7, :string
  	add_column :encuesta, :p4_39_8, :string
  	add_column :encuesta, :p4_40_1, :string
  	add_column :encuesta, :p4_40_2, :string
  	add_column :encuesta, :p4_40_3, :string
  	add_column :encuesta, :p4_40_4, :string
  	add_column :encuesta, :p4_40_5, :string
  	add_column :encuesta, :p4_40_6, :string
  	add_column :encuesta, :p4_40_7, :string
  	add_column :encuesta, :p4_40_8, :string
  	add_column :encuesta, :p4_41_1, :string
  	add_column :encuesta, :p4_41_2, :string
  	add_column :encuesta, :p4_41_3, :string
  	add_column :encuesta, :p4_41_4, :string
  	add_column :encuesta, :p4_41_5, :string
  	add_column :encuesta, :p4_41_6, :string
  	add_column :encuesta, :p4_41_7, :string
  	add_column :encuesta, :p4_41_8, :string
  	add_column :encuesta, :p4_42_1, :string
  	add_column :encuesta, :p4_42_2, :string
  	add_column :encuesta, :p4_42_3, :string
  	add_column :encuesta, :p4_42_4, :string
  	add_column :encuesta, :p4_42_5, :string
  	add_column :encuesta, :p4_42_6, :string
  	add_column :encuesta, :p4_42_7, :string
  	add_column :encuesta, :p4_42_8, :string
  	add_column :encuesta, :p4_42a_1, :string
  	add_column :encuesta, :p4_42a_2, :string
  	add_column :encuesta, :p4_42a_3, :string
  	add_column :encuesta, :p4_42a_4, :string
  	add_column :encuesta, :p4_42a_5, :string
  	add_column :encuesta, :p4_42a_6, :string
  	add_column :encuesta, :p4_42a_7, :string
  	add_column :encuesta, :p4_42a_8, :string
  	add_column :encuesta, :p4_42b_a_1, :string
  	add_column :encuesta, :p4_42b_a_2, :string
  	add_column :encuesta, :p4_42b_a_3, :string
  	add_column :encuesta, :p4_42b_a_4, :string
  	add_column :encuesta, :p4_42b_a_5, :string
  	add_column :encuesta, :p4_42b_a_6, :string
  	add_column :encuesta, :p4_42b_a_7, :string
  	add_column :encuesta, :p4_42b_a_8, :string
  	add_column :encuesta, :p4_42b_b_1, :string
  	add_column :encuesta, :p4_42b_b_2, :string
  	add_column :encuesta, :p4_42b_b_3, :string
  	add_column :encuesta, :p4_42b_b_4, :string
  	add_column :encuesta, :p4_42b_b_5, :string
  	add_column :encuesta, :p4_42b_b_6, :string
  	add_column :encuesta, :p4_42b_b_7, :string
  	add_column :encuesta, :p4_42b_b_8, :string

  end
end
