class Addcolumtoencuesta5modulo < ActiveRecord::Migration[5.2]
  def change

	add_column :encuesta, :p5_43_1_1, :string
  	add_column :encuesta, :p5_43_1_2, :string
  	add_column :encuesta, :p4_43_1_3, :string
  	add_column :encuesta, :p5_43_1_4, :string
  	add_column :encuesta, :p5_43_1_5, :string
  	add_column :encuesta, :p5_43_1_6, :string
  	add_column :encuesta, :p5_43_1_7, :string
  	add_column :encuesta, :p5_43_1_8, :string
  	add_column :encuesta, :p5_43_2_1, :string
  	add_column :encuesta, :p5_43_2_2, :string
  	add_column :encuesta, :p5_43_2_3, :string
  	add_column :encuesta, :p5_43_2_4, :string
  	add_column :encuesta, :p5_43_2_5, :string
  	add_column :encuesta, :p5_43_2_6, :string
  	add_column :encuesta, :p5_43_2_7, :string
  	add_column :encuesta, :p5_43_2_8, :string
  	add_column :encuesta, :p5_43_3_1, :string
  	add_column :encuesta, :p5_43_3_2, :string
  	add_column :encuesta, :p5_43_3_3, :string
  	add_column :encuesta, :p5_43_3_4, :string
  	add_column :encuesta, :p5_43_3_5, :string
  	add_column :encuesta, :p5_43_3_6, :string
  	add_column :encuesta, :p5_43_3_7, :string
  	add_column :encuesta, :p5_43_3_8, :string
  	add_column :encuesta, :p5_44_1, :string
  	add_column :encuesta, :p5_44_2, :string
  	add_column :encuesta, :p5_44_3, :string
  	add_column :encuesta, :p5_44_4, :string
  	add_column :encuesta, :p5_44_5, :string
  	add_column :encuesta, :p5_44_6, :string
  	add_column :encuesta, :p5_44_7, :string
  	add_column :encuesta, :p5_44_8, :string
	add_column :encuesta, :p5_44_b_1, :string
  	add_column :encuesta, :p5_44_b_2, :string
  	add_column :encuesta, :p5_44_b_3, :string
  	add_column :encuesta, :p5_44_b_4, :string
  	add_column :encuesta, :p5_44_b_5, :string
  	add_column :encuesta, :p5_44_b_6, :string
  	add_column :encuesta, :p5_44_b_7, :string
  	add_column :encuesta, :p5_44_b_8, :string
  	add_column :encuesta, :p5_45_1, :string
  	add_column :encuesta, :p5_45_2, :string
  	add_column :encuesta, :p5_45_3, :string
  	add_column :encuesta, :p5_45_4, :string
  	add_column :encuesta, :p5_45_5, :string
  	add_column :encuesta, :p5_45_6, :string
  	add_column :encuesta, :p5_45_7, :string
  	add_column :encuesta, :p5_45_8, :string

  	add_column :encuesta, :p5_46a_1, :string
  	add_column :encuesta, :p5_46a_2, :string
  	add_column :encuesta, :p5_46a_3, :string
  	add_column :encuesta, :p5_46a_4, :string
  	add_column :encuesta, :p5_46a_5, :string
  	add_column :encuesta, :p5_46a_6, :string
  	add_column :encuesta, :p5_46a_7, :string
  	add_column :encuesta, :p5_46a_8, :string
  	add_column :encuesta, :p5_46_b_1, :string
  	add_column :encuesta, :p5_46_b_2, :string
  	add_column :encuesta, :p5_46_b_3, :string
  	add_column :encuesta, :p5_46_b_4, :string
  	add_column :encuesta, :p5_46_b_5, :string
  	add_column :encuesta, :p5_46_b_6, :string
  	add_column :encuesta, :p5_46_b_7, :string
  	add_column :encuesta, :p5_46_b_8, :string

  	add_column :encuesta, :p5_47_1, :string
  	add_column :encuesta, :p5_47_2, :string
  	add_column :encuesta, :p5_47_3, :string
  	add_column :encuesta, :p5_47_4, :string
  	add_column :encuesta, :p5_47_5, :string
  	add_column :encuesta, :p5_47_6, :string
  	add_column :encuesta, :p5_47_7, :string
  	add_column :encuesta, :p5_47_8, :string

  end
end
