class Addcolumtoencuesta6modulo < ActiveRecord::Migration[5.2]
  def change

add_column :encuesta, :p6_48_1, :string
  	add_column :encuesta, :p6_48_2, :string
  	add_column :encuesta, :p6_48_3, :string
  	add_column :encuesta, :p6_48_4, :string
  	add_column :encuesta, :p6_48_5, :string
  	add_column :encuesta, :p6_48_6, :string
  	add_column :encuesta, :p6_48_7, :string
  	add_column :encuesta, :p6_48_8, :string
  	add_column :encuesta, :p6_49_1, :string
  	add_column :encuesta, :p6_49_2, :string
  	add_column :encuesta, :p6_49_3, :string
  	add_column :encuesta, :p6_49_4, :string
  	add_column :encuesta, :p6_49_5, :string
  	add_column :encuesta, :p6_49_6, :string
  	add_column :encuesta, :p6_49_7, :string
  	add_column :encuesta, :p6_49_8, :string

  	add_column :encuesta, :p6_50_1, :string
  	add_column :encuesta, :p6_50_2, :string
  	add_column :encuesta, :p6_50_3, :string
  	add_column :encuesta, :p6_50_4, :string
  	add_column :encuesta, :p6_50_5, :string
  	add_column :encuesta, :p6_50_6, :string
  	add_column :encuesta, :p6_50_7, :string
  	add_column :encuesta, :p6_50_8, :string

	add_column :encuesta, :p6_50_b_1, :string
  	add_column :encuesta, :p6_50_b_2, :string
  	add_column :encuesta, :p6_50_b_3, :string
  	add_column :encuesta, :p6_50_b_4, :string
  	add_column :encuesta, :p6_50_b_5, :string
  	add_column :encuesta, :p6_50_b_6, :string
  	add_column :encuesta, :p6_50_b_7, :string
  	add_column :encuesta, :p6_50_b_8, :string

  	add_column :encuesta, :p6_51_1_a, :string
  	add_column :encuesta, :p6_51_1_b, :string
  	add_column :encuesta, :p6_51_2_a, :string
  	add_column :encuesta, :p6_51_2_b, :string
  	add_column :encuesta, :p6_51_3_a, :string
  	add_column :encuesta, :p6_51_3_b, :string
  	add_column :encuesta, :p6_51_4_a, :string
  	add_column :encuesta, :p6_51_4_b, :string
  	add_column :encuesta, :p6_51_5_a, :string
  	add_column :encuesta, :p6_51_5_b, :string
  	add_column :encuesta, :p6_51_6_a, :string
  	add_column :encuesta, :p6_51_6_b, :string
  	add_column :encuesta, :p6_51_7_a, :string
  	add_column :encuesta, :p6_51_7_b, :string
  	add_column :encuesta, :p6_51_8_a, :string
  	add_column :encuesta, :p6_51_8_b, :string

  	add_column :encuesta, :p6_52_1, :string
  	add_column :encuesta, :p6_52_2, :string
  	add_column :encuesta, :p6_52_3, :string
  	add_column :encuesta, :p6_52_4, :string
  	add_column :encuesta, :p6_52_5, :string
  	add_column :encuesta, :p6_52_6, :string
  	add_column :encuesta, :p6_52_7, :string
  	add_column :encuesta, :p6_52_8, :string
  	add_column :encuesta, :p6_53_1, :string
  	add_column :encuesta, :p6_53_2, :string
  	add_column :encuesta, :p6_53_3, :string
  	add_column :encuesta, :p6_53_4, :string
  	add_column :encuesta, :p6_53_5, :string
  	add_column :encuesta, :p6_53_6, :string
  	add_column :encuesta, :p6_53_7, :string
  	add_column :encuesta, :p6_53_8, :string

  	add_column :encuesta, :p6_54_1_1a, :string
  	add_column :encuesta, :p6_54_1_2a, :string
  	add_column :encuesta, :p6_54_1_3a, :string
  	add_column :encuesta, :p6_54_2_1a, :string
  	add_column :encuesta, :p6_54_2_2a, :string
  	add_column :encuesta, :p6_54_2_3a, :string
  	add_column :encuesta, :p6_54_3_1a, :string
  	add_column :encuesta, :p6_54_3_2a, :string
  	add_column :encuesta, :p6_54_3_3a, :string
  	add_column :encuesta, :p6_54_4_1a, :string
  	add_column :encuesta, :p6_54_4_2a, :string
  	add_column :encuesta, :p6_54_4_3a, :string
  	add_column :encuesta, :p6_54_5_1a, :string
  	add_column :encuesta, :p6_54_5_2a, :string
  	add_column :encuesta, :p6_54_5_3a, :string
  	add_column :encuesta, :p6_54_6_1a, :string
  	add_column :encuesta, :p6_54_6_2a, :string
  	add_column :encuesta, :p6_54_6_3a, :string
  	add_column :encuesta, :p6_54_7_1a, :string
  	add_column :encuesta, :p6_54_7_2a, :string
  	add_column :encuesta, :p6_54_7_3a, :string
  	add_column :encuesta, :p6_54_8_1a, :string
  	add_column :encuesta, :p6_54_8_2a, :string
  	add_column :encuesta, :p6_54_8_3a, :string
	add_column :encuesta, :p6_54_1_1b, :string
  	add_column :encuesta, :p6_54_1_2b, :string
  	add_column :encuesta, :p6_54_1_3b, :string
  	add_column :encuesta, :p6_54_2_1b, :string
  	add_column :encuesta, :p6_54_2_2b, :string
  	add_column :encuesta, :p6_54_2_3b, :string
  	add_column :encuesta, :p6_54_3_1b, :string
  	add_column :encuesta, :p6_54_3_2b, :string
  	add_column :encuesta, :p6_54_3_3b, :string
  	add_column :encuesta, :p6_54_4_1b, :string
  	add_column :encuesta, :p6_54_4_2b, :string
  	add_column :encuesta, :p6_54_4_3b, :string
  	add_column :encuesta, :p6_54_5_1b, :string
  	add_column :encuesta, :p6_54_5_2b, :string
  	add_column :encuesta, :p6_54_5_3b, :string
  	add_column :encuesta, :p6_54_6_1b, :string
  	add_column :encuesta, :p6_54_6_2b, :string
  	add_column :encuesta, :p6_54_6_3b, :string
  	add_column :encuesta, :p6_54_7_1b, :string
  	add_column :encuesta, :p6_54_7_2b, :string
  	add_column :encuesta, :p6_54_7_3b, :string
  	add_column :encuesta, :p6_54_8_1b, :string
  	add_column :encuesta, :p6_54_8_2b, :string
  	add_column :encuesta, :p6_54_8_3b, :string

  	add_column :encuesta, :p6_55_1, :string
  	add_column :encuesta, :p6_55_2, :string
  	add_column :encuesta, :p6_55_3, :string
  	add_column :encuesta, :p6_55_4, :string
  	add_column :encuesta, :p6_55_5, :string
  	add_column :encuesta, :p6_55_6, :string
  	add_column :encuesta, :p6_55_7, :string
  	add_column :encuesta, :p6_55_8, :string

  	add_column :encuesta, :p6_56_1_1, :string
  	add_column :encuesta, :p6_56_1_2, :string
  	add_column :encuesta, :p6_56_1_3, :string
  	add_column :encuesta, :p6_56_1_4, :string
  	add_column :encuesta, :p6_56_1_5, :string
  	add_column :encuesta, :p6_56_2_1, :string
  	add_column :encuesta, :p6_56_2_2, :string
  	add_column :encuesta, :p6_56_2_3, :string
  	add_column :encuesta, :p6_56_2_4, :string
  	add_column :encuesta, :p6_56_2_5, :string
  	add_column :encuesta, :p6_56_3_1, :string
  	add_column :encuesta, :p6_56_3_2, :string
  	add_column :encuesta, :p6_56_3_3, :string
  	add_column :encuesta, :p6_56_3_4, :string
  	add_column :encuesta, :p6_56_3_5, :string
  	add_column :encuesta, :p6_56_4_1, :string
  	add_column :encuesta, :p6_56_4_2, :string
  	add_column :encuesta, :p6_56_4_3, :string
  	add_column :encuesta, :p6_56_4_4, :string
  	add_column :encuesta, :p6_56_4_5, :string
  	add_column :encuesta, :p6_56_5_1, :string
  	add_column :encuesta, :p6_56_5_2, :string
  	add_column :encuesta, :p6_56_5_3, :string
  	add_column :encuesta, :p6_56_5_4, :string
  	add_column :encuesta, :p6_56_5_5, :string
  	add_column :encuesta, :p6_56_6_1, :string
  	add_column :encuesta, :p6_56_6_2, :string
  	add_column :encuesta, :p6_56_6_3, :string
  	add_column :encuesta, :p6_56_6_4, :string
  	add_column :encuesta, :p6_56_6_5, :string
  	add_column :encuesta, :p6_56_7_1, :string
  	add_column :encuesta, :p6_56_7_2, :string
  	add_column :encuesta, :p6_56_7_3, :string
  	add_column :encuesta, :p6_56_7_4, :string
  	add_column :encuesta, :p6_56_7_5, :string
  	add_column :encuesta, :p6_56_8_1, :string
  	add_column :encuesta, :p6_56_8_2, :string
  	add_column :encuesta, :p6_56_8_3, :string
  	add_column :encuesta, :p6_56_8_4, :string
  	add_column :encuesta, :p6_56_8_5, :string

	add_column :encuesta, :p6_57_1, :string
  	add_column :encuesta, :p6_57_2, :string
  	add_column :encuesta, :p6_57_3, :string
  	add_column :encuesta, :p6_57_4, :string
  	add_column :encuesta, :p6_57_5, :string
  	add_column :encuesta, :p6_57_6, :string
  	add_column :encuesta, :p6_57_7, :string
  	add_column :encuesta, :p6_57_8, :string

  	add_column :encuesta, :p6_58a_1, :string
  	add_column :encuesta, :p6_58a_2, :string
  	add_column :encuesta, :p6_58a_3, :string
  	add_column :encuesta, :p6_58a_4, :string
  	add_column :encuesta, :p6_58a_5, :string
  	add_column :encuesta, :p6_58a_6, :string
  	add_column :encuesta, :p6_58a_7, :string
  	add_column :encuesta, :p6_58a_8, :string

	add_column :encuesta, :p6_58b_1, :string
  	add_column :encuesta, :p6_58b_2, :string
  	add_column :encuesta, :p6_58b_3, :string
  	add_column :encuesta, :p6_58b_4, :string
  	add_column :encuesta, :p6_58b_5, :string
  	add_column :encuesta, :p6_58b_6, :string
  	add_column :encuesta, :p6_58b_7, :string
  	add_column :encuesta, :p6_58b_8, :string


  end
end
