class Addcolumtoencuesta11modulo < ActiveRecord::Migration[5.2]
  def change

	add_column :encuesta, :p11_ta_1, :string
	add_column :encuesta, :p11_ta_a_2, :string
	add_column :encuesta, :p11_ta_a_3, :string
	add_column :encuesta, :p11_ta_a_4, :string
	add_column :encuesta, :p11_ta_a_5, :string
	add_column :encuesta, :p11_ta_a_6, :string
	add_column :encuesta, :p11_ta_a_7, :string
	add_column :encuesta, :p11_ta_a_8, :string
	add_column :encuesta, :p11_ta_a_9, :string
	add_column :encuesta, :p11_ta_a_10, :string
	add_column :encuesta, :p11_ta_b_2, :string
	add_column :encuesta, :p11_ta_b_3, :string
	add_column :encuesta, :p11_ta_b_4, :string
	add_column :encuesta, :p11_ta_b_5, :string
	add_column :encuesta, :p11_ta_b_6, :string
	add_column :encuesta, :p11_ta_b_7, :string
	add_column :encuesta, :p11_ta_b_8, :string
	add_column :encuesta, :p11_ta_b_9, :string
	add_column :encuesta, :p11_ta_b_10, :string
	add_column :encuesta, :p11_ta_c_2, :string
	add_column :encuesta, :p11_ta_c_3, :string
	add_column :encuesta, :p11_ta_c_4, :string
	add_column :encuesta, :p11_ta_c_5, :string
	add_column :encuesta, :p11_ta_c_6, :string
	add_column :encuesta, :p11_ta_c_7, :string
	add_column :encuesta, :p11_ta_c_8, :string
	add_column :encuesta, :p11_ta_c_9, :string
	add_column :encuesta, :p11_ta_c_10, :string
	add_column :encuesta, :p11_ta_d_2, :string
	add_column :encuesta, :p11_ta_d_3, :string
	add_column :encuesta, :p11_ta_d_4, :string
	add_column :encuesta, :p11_ta_d_5, :string
	add_column :encuesta, :p11_ta_d_6, :string
	add_column :encuesta, :p11_ta_d_7, :string
	add_column :encuesta, :p11_ta_d_8, :string
	add_column :encuesta, :p11_ta_d_9, :string
	add_column :encuesta, :p11_ta_d_10, :string
	add_column :encuesta, :p11_ta_e_2, :string
	add_column :encuesta, :p11_ta_e_3, :string
	add_column :encuesta, :p11_ta_e_4, :string
	add_column :encuesta, :p11_ta_e_5, :string
	add_column :encuesta, :p11_ta_e_6, :string
	add_column :encuesta, :p11_ta_e_7, :string
	add_column :encuesta, :p11_ta_e_8, :string
	add_column :encuesta, :p11_ta_e_9, :string
	add_column :encuesta, :p11_ta_e_10, :string
	add_column :encuesta, :p11_ta_f_2, :string
	add_column :encuesta, :p11_ta_f_3, :string
	add_column :encuesta, :p11_ta_f_4, :string
	add_column :encuesta, :p11_ta_f_5, :string
	add_column :encuesta, :p11_ta_f_6, :string
	add_column :encuesta, :p11_ta_f_7, :string
	add_column :encuesta, :p11_ta_f_8, :string
	add_column :encuesta, :p11_ta_f_9, :string
	add_column :encuesta, :p11_ta_f_10, :string
	add_column :encuesta, :p11_tb_1, :string
	add_column :encuesta, :p11_tb_2, :string
	add_column :encuesta, :p11_tb_3_a, :string
	add_column :encuesta, :p11_tb_3_b, :string
	add_column :encuesta, :p11_tb_3_c, :string
	add_column :encuesta, :p11_tb_3_d, :string
	add_column :encuesta, :p11_tb_4_a, :string
	add_column :encuesta, :p11_tb_4_b, :string
	add_column :encuesta, :p11_tb_4_c, :string
	add_column :encuesta, :p11_tb_4_d, :string
	add_column :encuesta, :p11_tb_5a_1, :string
	add_column :encuesta, :p11_tb_5a_2, :string
	add_column :encuesta, :p11_tb_5a_3, :string
	add_column :encuesta, :p11_tb_5b_1, :string
	add_column :encuesta, :p11_tb_5b_2, :string
	add_column :encuesta, :p11_tb_6a, :string
	add_column :encuesta, :p11_tb_6b, :string
	add_column :encuesta, :p11_tb_7, :string
	add_column :encuesta, :p11_tc_1, :string
	add_column :encuesta, :p11_tc_2, :string
	add_column :encuesta, :p11_tc_3_a, :string
	add_column :encuesta, :p11_tc_3_b, :string
	add_column :encuesta, :p11_tc_3_c, :string
	add_column :encuesta, :p11_tc_3_d, :string
	add_column :encuesta, :p11_tc_4_a, :string
	add_column :encuesta, :p11_tc_4_b, :string
	add_column :encuesta, :p11_tc_5_a, :string
	add_column :encuesta, :p11_tc_5_b, :string
	add_column :encuesta, :p11_tc_6, :string
	add_column :encuesta, :p11_td_1, :string
	add_column :encuesta, :p11_td_2, :string
	add_column :encuesta, :p11_td_3_a, :string
	add_column :encuesta, :p11_td_3_b, :string
	add_column :encuesta, :p11_td_4_a, :string
	add_column :encuesta, :p11_td_4_b, :string
	add_column :encuesta, :p11_td_5, :string
	add_column :encuesta, :p11_td_6, :string
	add_column :encuesta, :p11_te_1, :string
	add_column :encuesta, :p11_te_2, :string
	add_column :encuesta, :p11_te_2a_1, :string
	add_column :encuesta, :p11_te_2a_2, :string
	add_column :encuesta, :p11_te_2b_1, :string
	add_column :encuesta, :p11_te_2b_2, :string
	add_column :encuesta, :p11_te_2c_1, :string
	add_column :encuesta, :p11_te_2c_2, :string
	add_column :encuesta, :p11_te_2d_1, :string
	add_column :encuesta, :p11_te_2d_2, :string
	add_column :encuesta, :p11_te_2_e, :string
	add_column :encuesta, :p11_te_3, :string
	add_column :encuesta, :p11_te_3a_1, :string
	add_column :encuesta, :p11_te_3a_2, :string
	add_column :encuesta, :p11_te_3b_1, :string
	add_column :encuesta, :p11_te_3b_2, :string
	add_column :encuesta, :p11_te_3c_1, :string
	add_column :encuesta, :p11_te_3c_2, :string
	add_column :encuesta, :p11_te_3d_1, :string
	add_column :encuesta, :p11_te_3d_2, :string
	add_column :encuesta, :p11_te_3_e, :string
	add_column :encuesta, :p11_te_4, :string
	add_column :encuesta, :p11_te_4a_1, :string
	add_column :encuesta, :p11_te_4a_2, :string
	add_column :encuesta, :p11_te_4a_3, :string
	add_column :encuesta, :p11_te_4b_1, :string
	add_column :encuesta, :p11_te_4b_2, :string
	add_column :encuesta, :p11_te_4b_3, :string
	add_column :encuesta, :p11_te_4c_1, :string
	add_column :encuesta, :p11_te_4c_2, :string
	add_column :encuesta, :p11_te_4c_3, :string
	add_column :encuesta, :p11_te_4d_1, :string
	add_column :encuesta, :p11_te_4d_2, :string
	add_column :encuesta, :p11_te_4d_3, :string
	add_column :encuesta, :p11_te_4_e, :string


  end
end
